
version: '1'

services:
  hamar1-php:
    build:
      context: .
      dockerfile: config/Dockerfile
    image: mark12qwe/hamar:yes
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html

  hamar1-web:
    image: library/nginx:1.20.1
    ports:
      - "8086:80"
    depends_on:
      - hamar1-php
    volumes:
      - ./src:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf