apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ukf
data:
  default.conf: |
    server {
      # Replace this port with the right one for your requirements
      listen 80 default_server;
      server_name _;
      root /var/www/html;
      index index.php index.html;
    
    
      location \ {
      try_files $uri $uri/ /index.php?$query_string;
    }
    
      location ~ \.php$ {
      include fastcgi_params;
      try_files $uri = 404;
      fastcgi_pass   127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_param   PATH_INFO               $fastcgi_path_info;
      fastcgi_param   SCRIPT_FILENAME         $document_root$fastcgi_script_name;
    }
    }
