apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ukf
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 88
      targetPort: 80
      nodePort: 31534
  sessionAffinity: None
